nome = str(input('Olá qual é seu nome?'))
palavra = (input(f'Olá {nome}, me diga qualquer palavra para eu verificar para você algumas informações sobre: '))
print('Esse é o tipo primitivo: ', type(palavra))
print('A sua palavra é minúscula? ', palavra.islower())
print('A sua palavra é maiuscula? ', palavra.isupper())
print('A sua palavra é alfanumérica? ', palavra.isalnum())
print('A sua palavra é um número? ', palavra.isnumeric())
print('A sua palavra é alfabetizada? ', palavra.isalpha())
print('A sua palavra é capitalizada? ', palavra.istitle())
print(f'Bem {nome} essas foram as informações coletadas da sua palavra {palavra}.')
